spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todos?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: rlatnehd@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret-key: "sjudjdjxcbsdkfbkSLDBfkBSDFilkBSDlfikbSJDhfbSJLDBfizSHKDBf"